function CPH()
    vim.api.nvim_command(":close 2 ")
    vim.api.nvim_command(":close 2 ")
    vim.api.nvim_command(":close 2 ")
    vim.api.nvim_command(":vsplit input.txt")
    vim.api.nvim_command(":split extra.txt")
    vim.api.nvim_command(":split results.txt")
    vim.api.nvim_command(":TermExec size=40 cmd='./run_test.sh t'")
    vim.api.nvim_win_set_width(0, 40)
end
function CPHO()
    vim.api.nvim_command(":close 2 ")
    vim.api.nvim_command(":close 2 ")
    vim.api.nvim_command(":close 2 ")
    vim.api.nvim_command(":vsplit input.txt")
    vim.api.nvim_command(":split extra.txt")
    vim.api.nvim_command(":split results.txt")
    vim.api.nvim_command(":TermExec size=80 cmd='./run_test.sh o'")
    vim.api.nvim_win_set_width(0, 40)
end
function CPHD()
    vim.api.nvim_command(":close 2 ")
    vim.api.nvim_command(":close 2 ")
    vim.api.nvim_command(":close 2 ")
    vim.api.nvim_command(":vsplit input.txt")
    vim.api.nvim_command(":split extra.txt")
    vim.api.nvim_command(":split results.txt")
    vim.api.nvim_command(":TermExec size=80 cmd='./run_out.sh o'")
    vim.api.nvim_win_set_width(0, 40)
end
vim.keymap.set("n", "<leader>rt", ":CompetiTest receive testcases<CR>")
vim.keymap.set("n", "<leader>ra", ":CompetiTest add_testcase <CR>")
vim.keymap.set("n", "<leader>rr", ":CompetiTest run<CR>")
vim.keymap.set("n", "<leader>rs", ":CompetiTest show_ui<CR>")
